[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/sync-ideas/*"
  to = "/.netlify/functions/api/sync-ideas/:splat"
  status = 200

[functions]
  external_node_modules = ["@supabase/supabase-js", "express", "cors", "dotenv", "node-cron"]
